# Generated by Django 5.2.3 on 2025-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
