# Generated by Django 5.2.3 on 2025-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
